// Vercel catch-all serverless function for every /api/* request.
// The API bundle is generated by artifacts/api-server/build.mjs before
// Vercel packages this function.
import app from "../artifacts/ludo-game/api/_server/app.mjs";

export default app;
